wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707078862.256384
    t:
      1:
      - 55
      - 95
      3:
      - 13
      - 23
      4: 3.9.13
      5: 0.16.2
      8:
      - 1
      - 5
      13: darwin-x86_64
